export default {
  PRIMARY_COLOR: 'rgb(30, 147, 242)',
  SECONDARY_COLOR: 'rgb(238, 167, 2)',

  FONT_SIZE_SMALLEST: 8,
  FONT_SIZE_SMALLER: 10,
  FONT_SIZE_CUSTOM_SMALLER: 12,
  FONT_SIZE_SMALL1: 13,
  FONT_SIZE_SMALL: 14,
  FONT_SIZE_SMALL2: 15,
  FONT_SIZE_MEDIUM: 16,
  FONT_SIZE_MEDIUM2: 17,
  FONT_SIZE_LARGE: 18,
  FONT_SIZE_XLARGE: 24,
  FONT_SIZE_LARGEST: 32,

  FONT_WEIGHT_LIGHT: '200',
  FONT_WEIGHT_MEDIUM: '500',
  FONT_WEIGHT_BOLD: '700',
  FONT_WEIGHT_HEAVY: '800',
  BACKGROUND_COLOR_LIGHT: '#fff',
  CONTAINER_PADDING: 20,
  TEXT_INPUT_PADDING: 10,
  BUTTON_BACKGROUD_COLOR: '#27ae60',
  BUTTON_COLOR: '#fff',
  BUTTON_TEXTALIGN: 'center',
  BUTTON_CANCEL_BACKGROUD_COLOR: '#ffffff',
  BUTTON_CANCEL_COLOR: '#595B5A',

  MARGIN_BOTTOM: 10,
  MARGIN_SUBTITLE: 3,
  COLOR_INPUT: '#747474',
  BORDER_RADIUS: 4,

  BORDER_COLOR_FALSE: '#EF3742',
  TEXT_COLOR_FALSE: '#E23337',

  ROJO_BCI: "#E23337",
  AMARILLO_BCI: "#EEE016",
  VERDE_BCI: "#27ae60",
  AZUL_BCI: "#0b75bc",

  ITEM_CONTAINER_HEIGHT: 60,
  ITEM_TEXT_COLOR: '#595B5A',
  ITEM_TEXT_DATE_COLOR: '#8F8F8F',

  HEADER_TEXT_COLOR: '#fff',

  TEXT_INPUT_BACKGROUNDCOLOR: '#F4F4F4',

};